import React from 'react';
import { Clock3, ClipboardCheck, AlarmClock, Sparkles, CheckCircle2, AlertCircle, ArrowRight, BellRing } from 'lucide-react';
import SectionHeader from '../../components/platform/SectionHeader';

const TeacherHomeworkPage: React.FC = () => {
    return (
        <div className="space-y-10 pb-16 font-outfit">
            <SectionHeader
                eyebrow="Assignments"
                title="AI Homework Automation"
                description="Manage, distribute, and track smart assignments generated by AI based on individual student gaps."
            />

            <section className="grid gap-5 md:grid-cols-3">
                {[
                    { label: 'Completed', value: '14', icon: ClipboardCheck, tone: 'text-emerald-600', bg: 'bg-emerald-50', border: 'border-emerald-100' },
                    { label: 'Overdue', value: '5', icon: AlarmClock, tone: 'text-rose-600', bg: 'bg-rose-50', border: 'border-rose-100' },
                    { label: 'Avg AI Task Duration', value: '7 mins', icon: Clock3, tone: 'text-indigo-600', bg: 'bg-indigo-50', border: 'border-indigo-100' },
                ].map((item) => (
                    <div key={item.label} className={`rounded-[2rem] border ${item.border} bg-white p-6 shadow-sm flex items-center gap-4`}>
                        <div className={`h-14 w-14 rounded-2xl flex items-center justify-center ${item.bg} ${item.tone}`}>
                            <item.icon size={24} />
                        </div>
                        <div>
                            <div className="text-2xl font-black text-slate-900">{item.value}</div>
                            <div className="text-sm font-bold text-slate-500">{item.label}</div>
                        </div>
                    </div>
                ))}
            </section>

            <div className="grid gap-8 xl:grid-cols-[1.2fr,0.8fr]">
                <section className="rounded-[2.5rem] border border-slate-200 bg-white p-8 shadow-sm">
                    <div className="mb-6 flex items-center justify-between">
                        <div className="flex items-center gap-4">
                            <div className="flex h-12 w-12 items-center justify-center rounded-[1.2rem] bg-indigo-50 text-indigo-600">
                                <ClipboardCheck size={20} />
                            </div>
                            <div>
                                <h2 className="text-2xl font-black text-slate-900">This Week's Queue</h2>
                                <p className="text-sm font-medium text-slate-500">Targeted exercises tailored to immediate needs.</p>
                            </div>
                        </div>
                    </div>
                    
                    <div className="space-y-4">
                        {[
                            { student: 'Omar Fahad', task: 'School vocabulary review with voice recording', status: 'Pending', time: '10 mins', tone: 'amber' },
                            { student: 'Sara Ahmed', task: 'Picture-based conversational prompt', status: 'Completed', time: '6 mins', tone: 'emerald' },
                            { student: 'Layan Khalid', task: '3-word short sentence reordering', status: 'Overdue', time: '5 mins', tone: 'rose' },
                        ].map((row) => (
                            <div key={row.student} className="rounded-2xl border border-slate-100 bg-slate-50/50 p-5 hover:bg-white hover:shadow-md transition-all group flex flex-col sm:flex-row sm:items-center justify-between gap-4">
                                <div>
                                    <div className="flex items-center gap-3 mb-2">
                                        <div className="text-sm font-black text-slate-900">{row.student}</div>
                                        <div className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-0.5 text-[10px] font-black uppercase tracking-wider ${
                                            row.tone === 'emerald' ? 'bg-emerald-100 text-emerald-700' : 
                                            row.tone === 'rose' ? 'bg-rose-100 text-rose-700' : 'bg-amber-100 text-amber-700'
                                        }`}>
                                            {row.tone === 'emerald' ? <CheckCircle2 size={12} /> : row.tone === 'rose' ? <AlertCircle size={12} /> : <Clock3 size={12} />}
                                            {row.status}
                                        </div>
                                    </div>
                                    <div className="text-sm font-bold text-slate-700 mb-2">{row.task}</div>
                                    <div className="text-xs font-black text-slate-400">Est: {row.time}</div>
                                </div>
                                {row.tone === 'rose' && (
                                    <button className="flex items-center justify-center gap-2 rounded-xl bg-white border border-slate-200 px-4 py-2 text-xs font-black text-slate-700 hover:bg-slate-50 transition-colors">
                                        <BellRing size={14} />
                                        Remind
                                    </button>
                                )}
                            </div>
                        ))}
                    </div>
                </section>

                <section className="space-y-8">
                    <div className="rounded-[2.5rem] border border-indigo-100 bg-gradient-to-br from-indigo-50/80 to-white p-8 shadow-sm relative overflow-hidden">
                        <div className="absolute top-0 right-0 w-64 h-64 bg-indigo-100/50 rounded-full blur-3xl -translate-y-1/2 translate-x-1/2 pointer-events-none"></div>
                        
                        <div className="mb-6 flex items-center gap-4 relative z-10">
                            <div className="flex h-12 w-12 items-center justify-center rounded-[1.2rem] bg-indigo-600 text-white shadow-md shadow-indigo-200">
                                <Sparkles size={20} />
                            </div>
                            <div>
                                <h2 className="text-2xl font-black text-slate-900">AI Generator</h2>
                                <p className="text-sm font-medium text-slate-500">Create smart tasks instantly.</p>
                            </div>
                        </div>

                        <p className="text-sm font-medium leading-relaxed text-slate-600 mb-6 relative z-10">
                            The platform analyzes student gaps and suggests micro-assignments designed to take less than 10 minutes to maintain engagement.
                        </p>
                        
                        <div className="flex flex-col gap-3 relative z-10">
                            <button className="flex items-center justify-between rounded-xl bg-slate-950 px-5 py-4 text-sm font-black text-white hover:bg-slate-800 transition-colors shadow-lg shadow-slate-900/10 group">
                                <span className="flex items-center gap-2">
                                    <Sparkles size={18} className="text-indigo-400 group-hover:text-indigo-300 transition-colors" />
                                    Generate New Assignments
                                </span>
                                <ArrowRight size={16} className="text-slate-500 group-hover:text-white group-hover:translate-x-1 transition-all" />
                            </button>
                            <button className="flex items-center justify-between rounded-xl bg-white border border-slate-200 px-5 py-4 text-sm font-black text-slate-700 hover:bg-slate-50 transition-colors group">
                                <span className="flex items-center gap-2">
                                    <BellRing size={18} className="text-amber-500" />
                                    Send Bulk Reminders
                                </span>
                                <ArrowRight size={16} className="text-slate-400 group-hover:text-slate-700 group-hover:translate-x-1 transition-all" />
                            </button>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    );
};

export default TeacherHomeworkPage;
