import { Book, Country, EducationalStage, ForumTopic, Lesson } from './types';

export const COUNTRIES: Country[] = [
  { id: 'eg', name: 'مصر', flag: '🇪🇬', subdomain: 'eg' },
  { id: 'sa', name: 'السعودية', flag: '🇸🇦', subdomain: 'sa' },
  { id: 'ae', name: 'الإمارات', flag: '🇦🇪', subdomain: 'ae' },
  { id: 'jo', name: 'الأردن', flag: '🇯🇴', subdomain: 'jo' },
  { id: 'kw', name: 'الكويت', flag: '🇰🇼', subdomain: 'kw' },
];

export const BOOKS: Book[] = [
  {
    id: 'phonics-foundations',
    title: 'Phonics Foundations',
    subject: 'Phonics',
    grade: 1,
    stage: EducationalStage.PRIMARY,
    coverUrl: 'https://images.unsplash.com/photo-1516627145497-ae6968895b74?auto=format&fit=crop&w=900&q=80',
    author: 'Readmint Native Team',
    countryId: 'eg',
  },
  {
    id: 'my-first-words',
    title: 'My First 100 Words',
    subject: 'Vocabulary',
    grade: 1,
    stage: EducationalStage.PRIMARY,
    coverUrl: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=900&q=80',
    author: 'Readmint Native Team',
    countryId: 'sa',
  },
  {
    id: 'speak-in-sentences',
    title: 'Speak in Sentences',
    subject: 'Speaking',
    grade: 3,
    stage: EducationalStage.PRIMARY,
    coverUrl: 'https://images.unsplash.com/photo-1513258496099-48168024aec0?auto=format&fit=crop&w=900&q=80',
    author: 'Native Teacher Studio',
    countryId: 'ae',
  },
  {
    id: 'read-and-understand',
    title: 'Read and Understand',
    subject: 'Reading',
    grade: 4,
    stage: EducationalStage.PRIMARY,
    coverUrl: 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?auto=format&fit=crop&w=900&q=80',
    author: 'Readmint Literacy Lab',
    countryId: 'jo',
  },
  {
    id: 'grammar-for-kids',
    title: 'Grammar for Kids',
    subject: 'Grammar',
    grade: 5,
    stage: EducationalStage.PRIMARY,
    coverUrl: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=900&q=80',
    author: 'Native Teacher Studio',
    countryId: 'kw',
  },
];

export const LESSONS: Lesson[] = [
  {
    id: 'phonics-a-short',
    title: 'Short A with a Native Teacher',
    subject: 'Phonics',
    duration: '18 min',
    thumbnailUrl: 'https://images.unsplash.com/photo-1588072432836-e10032774350?auto=format&fit=crop&w=900&q=80',
    difficulty: 'Easy',
    grade: 1,
    countryId: 'eg',
  },
  {
    id: 'classroom-words',
    title: 'Classroom Words Kids Use Every Day',
    subject: 'Vocabulary',
    duration: '15 min',
    thumbnailUrl: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=900&q=80',
    difficulty: 'Easy',
    grade: 2,
    countryId: 'sa',
  },
  {
    id: 'simple-sentences',
    title: 'Build Simple Sentences',
    subject: 'Speaking',
    duration: '22 min',
    thumbnailUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=900&q=80',
    difficulty: 'Medium',
    grade: 3,
    countryId: 'ae',
  },
  {
    id: 'story-time-comprehension',
    title: 'Story Time and Comprehension',
    subject: 'Reading',
    duration: '20 min',
    thumbnailUrl: 'https://images.unsplash.com/photo-1516627145497-ae6968895b74?auto=format&fit=crop&w=900&q=80',
    difficulty: 'Medium',
    grade: 4,
    countryId: 'jo',
  },
  {
    id: 'questions-and-answers',
    title: 'Ask and Answer Questions',
    subject: 'Conversation',
    duration: '25 min',
    thumbnailUrl: 'https://images.unsplash.com/photo-1513258496099-48168024aec0?auto=format&fit=crop&w=900&q=80',
    difficulty: 'Hard',
    grade: 5,
    countryId: 'kw',
  },
];

export const MOCK_FORUM_TOPICS: ForumTopic[] = [
  {
    id: 'parent-progress',
    title: 'كيف أقرأ تقرير التقدم الأسبوعي لطفلي؟',
    author: 'أم يزن',
    replies: 18,
    views: 420,
    tags: ['الأهل', 'التقدم'],
    lastActive: 'منذ ساعة',
    countryId: 'eg',
    grade: 2,
  },
  {
    id: 'speaking-home',
    title: 'أنشطة منزلية بسيطة لرفع Speaking عند الطفل',
    author: 'Teacher Hana',
    replies: 11,
    views: 286,
    tags: ['speaking', 'home practice'],
    lastActive: 'منذ 3 ساعات',
    countryId: 'sa',
    grade: 3,
  },
  {
    id: 'kg-readiness',
    title: 'ما أفضل بداية للطفل في KG: phonics أم كلمات؟',
    author: 'أب راشد',
    replies: 24,
    views: 510,
    tags: ['KG', 'phonics'],
    lastActive: 'منذ يوم',
    countryId: 'ae',
    grade: 1,
  },
];
